import { manrope } from "@/lib/fonts";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-black">
        <main> {children}</main>

        <Toaster position="top-right" />
      </body>
    </html>
  );
}
